language: python
python:
  #  - "3.3" - Removed, travis CI don`t support this version actually
  #  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -r requirements_dev.txt
# command to run tests
script:
  - make test
  - make check-sec

before_deploy: sed -i "s/__version__ = \".*\"/__version__ = \"$TRAVIS_TAG\"/g" azkaban_cli/__version__.py

deploy:
  provider: pypi
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  skip_cleanup: true
  skip_existing: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
